import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import Layout from '../components/Layout';
import ProductGrid from '../components/ProductGrid';
import { connectToCollection } from '../lib/mongodb';
import { Product } from '../types/Product';
import { formatFetchedProducts } from '../utils/formatFetchedProducts';

const Home = ({ products }: { products: Product[] }) => {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="  lg:h-96 flex justify-center items-center fullscreen-container mb-12">
        <div className="text-center">
          <h1 className="text-5xl lg:text-8xl font-extralight mb-4">store.eth</h1>
          <h2 className="text-lg lg:text-xl ">A happy flower keeps on blooming 🌸</h2>
        </div>
      </div>
      <div className="flex justify-center">
        <ProductGrid products={products} />
      </div>
      <div className="w-full mb-16 flex justify-center">
        <Link href="/store">
          <a className="py-3 px-5 rounded  text-xl bg-black text-white">View products</a>
        </Link>
      </div>
    </Layout>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const collection = await connectToCollection();
  console.log(collection);
  const products = await collection.find({}).toArray();

  return {
    props: {
      products: formatFetchedProducts(products),
    },
  };
};

export default Home;
